import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { getServerSession } from "next-auth";
import Logout from "@/components/Logout";
import Login from "@/components/Login";
import SessionProvider from "@/context/AuthContext";
import ToasterContext from "@/context/ToasterContext";
import NavigationMenubar from "@/components/Navigation/NavigationMenubar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className="max-w-screen-2xl px-7 md:px-10 mx-auto">
        <SessionProvider>
          <NavigationMenubar />
          <div className="flex gap-1">
            {!!session && <Logout />}

            {!session && <Login />}
            <Link href={"/"}>Home</Link>
          </div>

          {children}
          {/* React Hot Toast */}
          <ToasterContext />
        </SessionProvider>
      </body>
    </html>
  );
}
